import excavator from "../../assets/malzeme.png";
import bulldozer from "../../assets/malzeme.png";
import crane from "../../assets/malzeme.png";

export const machineList = [
    {
        id: 1,
        name: "XXXXXXXXXXXXX",
        price: 1,
        image: excavator,
        aosDelay: "0",
        type: "XXXXXXXXXXXXX",
        condition: "XXXXXXXXXXXXX",
        location: "Konya, Turkey",
    },
    {
        id: 2,
        name: "XXXXXXXXXXXXX",
        price: 2,
        image: bulldozer,
        aosDelay: "500",
        type: "XXXXXXXXXXXXX",
        condition: "XXXXXXXXXXXXX",
        location: "Konya, Turkey",
    },
    {
        id: 3,
        name: "XXXXXXXXXXXXX",
        price: 3,
        image: crane,
        aosDelay: "1000",
        type: "XXXXXXXXXXXXX",
        condition: "XXXXXXXXXXXXX",
        location: "Konya, Turkey",
    },
    {
        id: 4,
        name: "XXXXXXXXXXXXX",
        price: 4,
        image: excavator,
        aosDelay: "0",
        type: "XXXXXXXXXXXXX",
        condition: "XXXXXXXXXXXXX",
        location: "Konya, Turkey",
    },
    {
        id: 5,
        name: "XXXXXXXXXXXXX",
        price: 5,
        image: bulldozer,
        aosDelay: "500",
        type: "XXXXXXXXXXXXX",
        condition: "XXXXXXXXXXXXX",
        location: "Konya, Turkey",
    },
    {
        id: 6,
        name: "XXXXXXXXXXXXX",
        price: 6,
        image: crane,
        aosDelay: "1000",
        type: "XXXXXXXXXXXXX",
        condition: "XXXXXXXXXXXXX",
        location: "Konya, Turkey",
    },
    {
        id: 7,
        name: "XXXXXXXXXXXXX",
        price: 7,
        image: excavator,
        aosDelay: "0",
        type: "XXXXXXXXXXXXX",
        condition: "XXXXXXXXXXXXX",
        location: "Konya, Turkey",
    },
    {
        id: 8,
        name: "XXXXXXXXXXXXX",
        price: 8,
        image: bulldozer,
        aosDelay: "500",
        type: "XXXXXXXXXXXXX",
        condition: "XXXXXXXXXXXXX",
        location: "Konya, Turkey",
    },
    {
        id: 9,
        name: "XXXXXXXXXXXXX",
        price: 9,
        image: crane,
        aosDelay: "1000",
        type: "XXXXXXXXXXXXX",
        condition: "XXXXXXXXXXXXX",
        location: "Konya, Turkey",
    },
];